

# Main Window
ui/ui_MainWindow.h:
	uic ui/MainWindow.ui -o ui/ui_MainWindow.h

# About
ui/ui_About.h:
	uic ui/About.ui -o ui/ui_About.h

# Preferences
ui/ui_Preferences.h:
	uic ui/Preferences.ui -o ui/ui_Preferences.h

# Property Wizard
ui/ui_PropertyWizard.h:
	uic ui/PropertyWizard.ui -o ui/ui_PropertyWizard.h

# Find and replace Wizard
ui/ui_FindReplace.h:
	uic ui/FindReplace.ui -o ui/ui_FindReplace.h
