name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-linux:
    # Builds `sstamina`, `libstamina.so`, and `xstamina` for Linux x86-64 bit (ELF Format)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get Dependencies
      run: sudo apt-get install -y libqt5-dev libkf5xmlgui-dev libkf5textwidgets-dev libkf5kio-dev libkf5texteditor-dev qtbase5-dev qtdeclarative5-dev libqt5svg5-dev libkf5i18n-dev libkf5coreaddons-dev extra-cmake-modules


    - name: UIC Build
      # Install the necessary stuff for the GUI
      working-directory: ${{github.workspace}}/src/stamina/gui
      run: make

    - name: Clone Storm
      run: git clone https://github.com/moves-rwth/storm ${{github.workspace}}/storm

    - name: Configure Storm Cmake
      run: cmake ${{github.workspace}}/storm -B ${{github.workspace}}/storm/build

    - name: Build Storm
      run: cmake --build ${{github.workspace}}/storm/build

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DBUILD_GUI=On -DSTORM_PATH=${{github.workspace}}/storm

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build

      # Will add this when we add unit tests
      # - name: Test
      # working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      # run: ctest -C ${{env.BUILD_TYPE}}

  # Builds the
